### ISSUE TITLE
Error: Unable to retrieve access token

### ISSUE THREAD

**Issue by Egedk** [mkvd/smarttv-twitch#34]
Thanks for the greatest app for samsung smart tv. But yesterday, when i try to see twich tv, i get this error, and my friend also get this error: Unable to retrieve access token...
Its a samsung smarttv 7005 2014

**Comment by Semerket** [comment]
Hey 

I Installed the App just now, also tried to update, but i get this error 60% of the Time :-/
If needed i have a Samsung Smart Tv Led 40 ue40eh5300

But also thanks for the App :)

**Comment by gazkhul** [comment]
@mkvd Спасибо за приложение. Только установил. Все работает, кроме выбора канала. Ошибка в назавании темы. UE48H6200AK
