### ISSUE TITLE
Instructions for hosting your own app sync server

### ISSUE THREAD

**Issue by gurka** [mkvd/smarttv-twitch#47]
Hi,

I think that there should be instructions to host your own app sync server with the Twitch app, for many reasons:

* Safety. I don't feel comfortable letting my TV sync apps with an (in reality) unknown server.
* Availability. The Twitch app can be installed even if the official server is down.
* Compatibility. I assume the official server always host the latest version of the Twitch App. What if my TV does not support the latest version for some reason, and I would want to install a previous version? If I were running my own app sync server I could just checkout any previous version/commit and host that version.

Either a short description in the README or a link to somewhere where it's explained how to setup your own app sync server would be suffice. Maybe it's enough to clone the repo and host that directory via HTTP. No domain name or subdirectories, just http://[ip]/ ?

**Comment by easyMaxi** [comment]
I think for the normal user creating the own server is way to complicated. Please correct me if I'm wrong! But maybe we should discuss committing the app to the official store ...

For the more experienced user maybe this link is enough? http://www.samsungdforum.com/Guide/?FolderName=art00013&FileName=index.html

**Comment by gurka** [comment]
Yes, it probably is too complicated for normal users. I don't know about the requirements needed to get accepted to the official store, but it's a good idea.

Anyway, I think that the link should be added to the README.md. I know how to setup http-servers and stuff like that, but I had no idea how the Samsung SmartTV App Sync stuff worked - so that link really helped me out!

**Comment by Gh0sty** [comment]
All you need is to run a local webserver on your PC/Laptop within your LAN.
There are installers like EasyPHP or XAMPP that will allow you to run a webserver but they come with stuff like PHP and MySQL which you don't need at all to host you own app sync server.
The easiest way is to download and run nginx for windows: http://nginx.org/en/docs/windows.html
Then place the TwitchTV.zip and the widgetlist.xml files in the html folder of nginx: (C:\nginx-1.9.0\html) and modify the IP address of the <download> tag of widgetlist.xml to your LAN IP address of your server and maybe also the <compression size= ...> tag if it doesn't fit the zip file.

**Comment by monkeyphysics** [comment]
Thanks for documenting these tips, guys. I will close this issue, as it's not really a software issue.
