### ISSUE TITLE
Server not responding

### ISSUE THREAD

**Issue by maiconsc** [mkvd/smarttv-twitch#51]
Hi! I tried to install the app on my Samsung Smart TV but got an ERROR_DEVELOPMENT_002. So I tried to ping from my pc to the IP 188.226.130.26 and it not responds. Did you can fix it? Maybe some new IP or restart the server? Thanks a lot.

**Comment by monkeyphysics** [comment]
You can't ping the IP, it has pings blocked in the firewall. You can verify the server is online by checking the file `http://188.226.130.26/widgetlist.xml`, which is the same file your Samsung TV will use.
