### ISSUE TITLE
Error: Unable to load stream data

### ISSUE THREAD

**Issue by carl211011** [mkvd/smarttv-twitch#58]
I installed the app and such but when I open twitch it displays Retrying(1/15) and if it reaches 15 it shows a message Error: Unable to load stream data.

Device Name: [TV]UA32EH4500

**Comment by carl211011** [comment]
I am connnected to the internet too. So I don't know why this message appears

**Comment by EHadoux** [comment]
Same problem here. Why did you close the issue?

**Comment by barthorre** [comment]
I'm having the same issue. Any tips?

**Comment by carl211011** [comment]
I just need to update the firmware of the TV.
