### ISSUE TITLE
Can't install the app using IP or USB, can't figure out how to make Apache Server. Please Help.

### ISSUE THREAD

**Issue by aboumich** [mkvd/smarttv-twitch#96]
Hello, 

as mentioned in issue 94, the IP is not working anymore. @Piaero said in that thread:

> SOLUTION: Looks like IP is down and you can't install widgets from USB after certain firmware update
You need to get apache server
modify widgetlist.xml to match your IP and localisation. Also put the app zip in the folder
update as you would normally do using your computer's IP

How would you do this on windows? Any other options? Anything easier? I'm looking for a quick solution, I would like to watch the CS:GO Major on my TV.

Thanks,

Aboumich

**Comment by aboumich** [comment]
I've given up. I get DEVELOPPER_ERROR_2 on my TV, no record in logs TV accessing it. I can only get access if I put the port number but it wont let me. Please help.

**Comment by Piaero** [comment]
What tv model you've got?

**Comment by aboumich** [comment]
I'm stupid. The entire time e-league was streaming the csgo major on youtube. I'm streaming it there. Thanks.
